version: '3'
services:
  php:
    build: docker
    volumes:
      - .:/var/www/html
    depends_on:
      - kafka
    networks:
      - laravel-kafka

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    platform: linux/amd64
    hostname: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - laravel-kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    platform: linux/amd64
    hostname: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - laravel-kafka

networks:
  laravel-kafka:
    driver: bridge
