version: '3.7'

services:
  php:
    build: docker
    volumes:
      - .:/var/www/html
    depends_on:
      - kafka
    networks:
      - kafka

  zookeeper:
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      - ZOOKEEPER_CLIENT_PORT=32181
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SYNC_LIMIT=2
    networks:
      - kafka

  kafka:
    image: 'confluentinc/cp-kafka:latest'
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
      - KAFKA_ADVERTISED_LISTENERS=kafka:29092
      - KAFKA_BROKER_ID=2
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
    networks:
      - kafka

  schema-registry:
    image: 'confluentinc/cp-schema-registry:latest'
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=kafka:29092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=schema-registry:8081
      - SCHEMA_REGISTRY_DEBUG=true
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka

#  kafka-connect:
#    image: 'confluentinc/cp-kafka-connect:latest'
#    environment:
#      - CONNECT_BOOTSTRAP_SERVERS=kafka:29092
#      - CONNECT_REST_PORT=28082
#      - CONNECT_GROUP_ID="quickstart"
#      - CONNECT_CONFIG_STORAGE_TOPIC="quickstart-config"
#      - CONNECT_OFFSET_STORAGE_TOPIC="quickstart-offsets"
#      - CONNECT_STATUS_STORAGE_TOPIC="quickstart-status"
#      - CONNECT_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
#      - CONNECT_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
#      - CONNECT_INTERNAL_KEY_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
#      - CONNECT_INTERNAL_VALUE_CONVERTER="org.apache.kafka.connect.json.JsonConverter"
#      - CONNECT_REST_ADVERTISED_HOST_NAME="kafka-connect"
#      - CONNECT_PLUGIN_PATH=/usr/share/java
#      - CONNECT_LOG4J_LOGGERS="org.apache.kafka.connect=DEBUG"
#    depends_on:
#      - schema-registry
#    networks:
#      - kafka

#  control-center:
#    image: 'confluentinc/cp-kafka-connect-base'
#    container_name: control-center
#    ulimits:
#      - nofile=16384:16384
#    environment:
#      - CONTROL_CENTER_BOOTSTRAP_SERVERS=kafka:29092
#      - CONTROL_CENTER_REPLICATION_FACTOR=1
#      - CONTROL_CENTER_CONNECT_CLUSTER=kafka-connect:28082
#    volumes:
#      - /mnt/control-center/data:/var/lib/confluent-control-center
#    depends_on:
#      - kafka-connect
#      - schema-registry
#      - kafka
#    networks:
#      - kafka

networks:
  kafka:
    driver: bridge